gotify:
  # URL of your gotify server
  url: https://gotify.yourdomain.com
  # Create an API Token in GOTIFY
  apiToken: "asdjklreujiot"
matrix:
  # Your homeserver.
  homeserverURL: "https://chat.yourdomain.com"
  # Matrix domain. Optional if it matches just the hostname.
  matrixDomain: "yourdomain.com"
  # Username. Must already exist on the server
  username: "botname"
  # Get an API token from Matrix
  token: "dsfjgkldsfjgkl"
  roomID: "!sdjfklsdjlf:yourdomain.com"
  # If you want to always use the same device ID, set it here.
  # Leave blank or unset for a random device ID
  deviceID: ""
  # Set this to true if the room is encrypted, false otherwise
  encrypted: true
logging:
  # can be DEBUG, INFO, WARN, ERROR
  level: INFO
  # can be PLAIN, COLOR, JSON
  format: color
downloadFromHostAllowlist:
  # Set this to allow image downloading from gotify messages. The format is regexp.
  # If you really want to allow all hosts, set this to ".*"
  - ".*\\.yourdomain\\.com"
  - ".*\\.trusteddomain\\.com"
