gotify:
  # URL of your gotify server
  url: https://gotify.yourdomain.com
  # Create an API Token in GOTIFY
  apiToken: "asdjklreujiot"
matrix:
  # Your homeserver.
  homeserverURL: "https://chat.yourdomain.com"
  # Matrix domain. Optional if it matches just the hostname.
  matrixDomain: "yourdomain.com"
  # Username. Must already exist on the server
  username: "botname"
  # Password for the user
  password: "dsfjgkldsfjgkl"
  roomID: "!sdjfklsdjlf:yourdomain.com"
logging:
  # can be DEBUG, INFO, WARN, ERROR
  level: INFO
  # can be PLAIN, COLOR, JSON
  format: color
downloader:
  allowedHosts:
    # Set this to allow image downloading from gotify messages. The format is regexp.
    # If you really want to allow all hosts, set this to ".*"
    - ".*\\.yourdomain\\.com"
    - ".*\\.trusteddomain\\.com"
