// Code generated by pegomock. DO NOT EDIT.
// Source: gotify_matrix_bot/matrix (interfaces: MautrixClient)

package matrix_test

import (
	context "context"
	pegomock "github.com/petergtz/pegomock/v4"
	mautrix "maunium.net/go/mautrix"
	event "maunium.net/go/mautrix/event"
	id "maunium.net/go/mautrix/id"
	"reflect"
	"time"
)

type MockMautrixClient struct {
	fail func(message string, callerSkip ...int)
}

func NewMockMautrixClient(options ...pegomock.Option) *MockMautrixClient {
	mock := &MockMautrixClient{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockMautrixClient) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockMautrixClient) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockMautrixClient) JoinedMembers(ctx context.Context, roomID id.RoomID) (*mautrix.RespJoinedMembers, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockMautrixClient().")
	}
	_params := []pegomock.Param{ctx, roomID}
	_result := pegomock.GetGenericMockFrom(mock).Invoke("JoinedMembers", _params, []reflect.Type{reflect.TypeOf((**mautrix.RespJoinedMembers)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var _ret0 *mautrix.RespJoinedMembers
	var _ret1 error
	if len(_result) != 0 {
		if _result[0] != nil {
			_ret0 = _result[0].(*mautrix.RespJoinedMembers)
		}
		if _result[1] != nil {
			_ret1 = _result[1].(error)
		}
	}
	return _ret0, _ret1
}

func (mock *MockMautrixClient) SendMessageEvent(ctx context.Context, roomID id.RoomID, eventType event.Type, content interface{}, extra ...mautrix.ReqSendEvent) (*mautrix.RespSendEvent, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockMautrixClient().")
	}
	_params := []pegomock.Param{ctx, roomID, eventType, content}
	for _, param := range extra {
		_params = append(_params, param)
	}
	_result := pegomock.GetGenericMockFrom(mock).Invoke("SendMessageEvent", _params, []reflect.Type{reflect.TypeOf((**mautrix.RespSendEvent)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var _ret0 *mautrix.RespSendEvent
	var _ret1 error
	if len(_result) != 0 {
		if _result[0] != nil {
			_ret0 = _result[0].(*mautrix.RespSendEvent)
		}
		if _result[1] != nil {
			_ret1 = _result[1].(error)
		}
	}
	return _ret0, _ret1
}

func (mock *MockMautrixClient) Sync() error {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockMautrixClient().")
	}
	_params := []pegomock.Param{}
	_result := pegomock.GetGenericMockFrom(mock).Invoke("Sync", _params, []reflect.Type{reflect.TypeOf((*error)(nil)).Elem()})
	var _ret0 error
	if len(_result) != 0 {
		if _result[0] != nil {
			_ret0 = _result[0].(error)
		}
	}
	return _ret0
}

func (mock *MockMautrixClient) VerifyWasCalledOnce() *VerifierMockMautrixClient {
	return &VerifierMockMautrixClient{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockMautrixClient) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockMautrixClient {
	return &VerifierMockMautrixClient{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockMautrixClient) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockMautrixClient {
	return &VerifierMockMautrixClient{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockMautrixClient) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockMautrixClient {
	return &VerifierMockMautrixClient{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockMautrixClient struct {
	mock                   *MockMautrixClient
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockMautrixClient) JoinedMembers(ctx context.Context, roomID id.RoomID) *MockMautrixClient_JoinedMembers_OngoingVerification {
	_params := []pegomock.Param{ctx, roomID}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "JoinedMembers", _params, verifier.timeout)
	return &MockMautrixClient_JoinedMembers_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockMautrixClient_JoinedMembers_OngoingVerification struct {
	mock              *MockMautrixClient
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockMautrixClient_JoinedMembers_OngoingVerification) GetCapturedArguments() (context.Context, id.RoomID) {
	ctx, roomID := c.GetAllCapturedArguments()
	return ctx[len(ctx)-1], roomID[len(roomID)-1]
}

func (c *MockMautrixClient_JoinedMembers_OngoingVerification) GetAllCapturedArguments() (_param0 []context.Context, _param1 []id.RoomID) {
	_params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(_params) > 0 {
		if len(_params) > 0 {
			_param0 = make([]context.Context, len(c.methodInvocations))
			for u, param := range _params[0] {
				_param0[u] = param.(context.Context)
			}
		}
		if len(_params) > 1 {
			_param1 = make([]id.RoomID, len(c.methodInvocations))
			for u, param := range _params[1] {
				_param1[u] = param.(id.RoomID)
			}
		}
	}
	return
}

func (verifier *VerifierMockMautrixClient) SendMessageEvent(ctx context.Context, roomID id.RoomID, eventType event.Type, content interface{}, extra ...mautrix.ReqSendEvent) *MockMautrixClient_SendMessageEvent_OngoingVerification {
	_params := []pegomock.Param{ctx, roomID, eventType, content}
	for _, param := range extra {
		_params = append(_params, param)
	}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "SendMessageEvent", _params, verifier.timeout)
	return &MockMautrixClient_SendMessageEvent_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockMautrixClient_SendMessageEvent_OngoingVerification struct {
	mock              *MockMautrixClient
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockMautrixClient_SendMessageEvent_OngoingVerification) GetCapturedArguments() (context.Context, id.RoomID, event.Type, interface{}, []mautrix.ReqSendEvent) {
	ctx, roomID, eventType, content, extra := c.GetAllCapturedArguments()
	return ctx[len(ctx)-1], roomID[len(roomID)-1], eventType[len(eventType)-1], content[len(content)-1], extra[len(extra)-1]
}

func (c *MockMautrixClient_SendMessageEvent_OngoingVerification) GetAllCapturedArguments() (_param0 []context.Context, _param1 []id.RoomID, _param2 []event.Type, _param3 []interface{}, _param4 [][]mautrix.ReqSendEvent) {
	_params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(_params) > 0 {
		if len(_params) > 0 {
			_param0 = make([]context.Context, len(c.methodInvocations))
			for u, param := range _params[0] {
				_param0[u] = param.(context.Context)
			}
		}
		if len(_params) > 1 {
			_param1 = make([]id.RoomID, len(c.methodInvocations))
			for u, param := range _params[1] {
				_param1[u] = param.(id.RoomID)
			}
		}
		if len(_params) > 2 {
			_param2 = make([]event.Type, len(c.methodInvocations))
			for u, param := range _params[2] {
				_param2[u] = param.(event.Type)
			}
		}
		if len(_params) > 3 {
			_param3 = make([]interface{}, len(c.methodInvocations))
			for u, param := range _params[3] {
				_param3[u] = param.(interface{})
			}
		}
		_param4 = make([][]mautrix.ReqSendEvent, len(c.methodInvocations))
		for u := 0; u < len(c.methodInvocations); u++ {
			_param4[u] = make([]mautrix.ReqSendEvent, len(_params)-4)
			for x := 4; x < len(_params); x++ {
				if _params[x][u] != nil {
					_param4[u][x-4] = _params[x][u].(mautrix.ReqSendEvent)
				}
			}
		}
	}
	return
}

func (verifier *VerifierMockMautrixClient) Sync() *MockMautrixClient_Sync_OngoingVerification {
	_params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Sync", _params, verifier.timeout)
	return &MockMautrixClient_Sync_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockMautrixClient_Sync_OngoingVerification struct {
	mock              *MockMautrixClient
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockMautrixClient_Sync_OngoingVerification) GetCapturedArguments() {
}

func (c *MockMautrixClient_Sync_OngoingVerification) GetAllCapturedArguments() {
}
